# Generated by Django 6.1 on 2026-09-02 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('services', models.JSONField(default=list, help_text='List of services offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location', 'is_open'], name='mechanics_m_locatio_8a2e9c_idx'), models.Index(fields=['rating'], name='mechanics_m_rating_bf8409_idx'), models.Index(fields=['name'], name='mechanics_m_name_899d71_idx')],
            },
        ),
    ]
